name: Integración continua (CI) de Node.js

on:

push:

branches:

main
pull_request:

branches:

main

jobs:

build:

runs-on: ubuntu-latest

strategy:

matrix:
node-version: [20.x]

steps:

name: Clonar repositorio

uses: actions/checkout@v3

name: Configurar Node.js

uses: actions/setup-node@v3

with:

node-version: ${{ matrix.node-version }}

name: Instalar dependencias
run: npm install

name: Iniciar aplicación

run: npm start
